// Danh sách quốc gia hỗ trợ bởi api.zippopotam.us (chuẩn ISO 3166-1 alpha-2)
export const COUNTRIES = [
  { code: "US", name: "Hoa Kỳ",          placeholder: "90210" },
  { code: "GB", name: "Vương quốc Anh",  placeholder: "SW1A 1AA" },
  { code: "CA", name: "Canada",          placeholder: "K1A 0A6" },
  { code: "AU", name: "Úc",              placeholder: "2000" },
  { code: "DE", name: "Đức",             placeholder: "10115" },
  { code: "FR", name: "Pháp",            placeholder: "75001" },
  { code: "ES", name: "Tây Ban Nha",     placeholder: "28001" },
  { code: "IT", name: "Ý",              placeholder: "00100" },
  { code: "NL", name: "Hà Lan",          placeholder: "1011 AB" },
  { code: "BE", name: "Bỉ",             placeholder: "1000" },
  { code: "CH", name: "Thụy Sĩ",        placeholder: "8001" },
  { code: "AT", name: "Áo",             placeholder: "1010" },
  { code: "SE", name: "Thụy Điển",      placeholder: "111 29" },
  { code: "NO", name: "Na Uy",           placeholder: "0150" },
  { code: "DK", name: "Đan Mạch",       placeholder: "1050" },
  { code: "FI", name: "Phần Lan",       placeholder: "00100" },
  { code: "PL", name: "Ba Lan",          placeholder: "00-001" },
  { code: "PT", name: "Bồ Đào Nha",     placeholder: "1100-001" },
  { code: "IE", name: "Ireland",         placeholder: "D01 F5P2" },
  { code: "JP", name: "Nhật Bản",       placeholder: "100-0001" },
  { code: "IN", name: "Ấn Độ",          placeholder: "110001" },
  { code: "MX", name: "Mexico",          placeholder: "06600" },
  { code: "BR", name: "Brazil",          placeholder: "01310-100" },
  { code: "AR", name: "Argentina",       placeholder: "C1000AAA" },
  { code: "SG", name: "Singapore",       placeholder: "018956" },
  { code: "MY", name: "Malaysia",        placeholder: "50450" },
  { code: "TH", name: "Thái Lan",       placeholder: "10200" },
  { code: "PH", name: "Philippines",     placeholder: "1000" },
  { code: "ID", name: "Indonesia",       placeholder: "10110" },
  { code: "NZ", name: "New Zealand",     placeholder: "6011" },
  { code: "ZA", name: "Nam Phi",         placeholder: "8001" },
  { code: "TR", name: "Thổ Nhĩ Kỳ",    placeholder: "34000" },
  { code: "RU", name: "Nga",            placeholder: "101000" },
  { code: "CZ", name: "Séc",            placeholder: "110 00" },
  { code: "SK", name: "Slovakia",        placeholder: "811 01" },
  { code: "HU", name: "Hungary",         placeholder: "1011" },
  { code: "RO", name: "Romania",         placeholder: "010011" },
  { code: "GR", name: "Hy Lạp",         placeholder: "104 31" },
  { code: "HR", name: "Croatia",         placeholder: "10000" },
  { code: "BG", name: "Bulgaria",        placeholder: "1000" },
  { code: "LT", name: "Litva",           placeholder: "01001" },
  { code: "LV", name: "Latvia",          placeholder: "LV-1001" },
  { code: "EE", name: "Estonia",         placeholder: "10111" },
  { code: "SI", name: "Slovenia",        placeholder: "1000" },
  { code: "LU", name: "Luxembourg",      placeholder: "1009" },
  { code: "IS", name: "Iceland",         placeholder: "101" },
  { code: "LI", name: "Liechtenstein",   placeholder: "9490" },
  { code: "MD", name: "Moldova",         placeholder: "2001" },
  { code: "UA", name: "Ukraine",         placeholder: "01001" },
  { code: "GE", name: "Georgia",         placeholder: "0105" },
  { code: "AM", name: "Armenia",         placeholder: "0001" },
  { code: "KZ", name: "Kazakhstan",      placeholder: "010000" },
  { code: "IL", name: "Israel",          placeholder: "7192800" },
  { code: "ZM", name: "Zambia",          placeholder: "10101" },
  { code: "MZ", name: "Mozambique",      placeholder: "1101" },
  { code: "MA", name: "Maroc",           placeholder: "10001" },
  { code: "PE", name: "Peru",            placeholder: "Lima 1" },
  { code: "CO", name: "Colombia",        placeholder: "110111" },
  { code: "KR", name: "Hàn Quốc",         placeholder: "03000" },
  { code: "TW", name: "Đài Loan",         placeholder: "100" },
];
